import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Route 4",
  description: "Generated by create next app",
};

const Route4 = () => {
  return (
    <div>
      <div className="container mx-auto px-4 py-2">
        <div className="space-y-10">Route 4</div>
      </div>
    </div>
  );
};

export default Route4;
