import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Route 2",
  description: "Generated by create next app",
};

const Route2 = () => {
  return (
    <div>
      <div className="container mx-auto px-4 py-2">
        <div className="space-y-10">Route 2</div>
      </div>
    </div>
  );
};

export default Route2;
