import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <div className="container mx-auto px-4 py-2">
        <div className="space-y-10">Home</div>
      </div>
    </div>
  );
}
